name: Build release

on:
  push:
    branches:
      - master
      - develop
    tags:
      - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest # Keep only Windows build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Disable git core.autocrlf
        run: git config --global core.autocrlf false
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node 14.21.3
        uses: actions/setup-node@v3
        with:
          node-version: '14.21.3'
      - name: Setup node_modules cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install package dependencies
        run: yarn install
      - name: Test
        run: yarn test
      - name: Build app/
        run: yarn build
        env:
          NODE_ENV: production
          BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      - uses: ./workspaces/desktop-release-action
        with:
          win_csc_link: ${{ secrets.WIN_CSC_LINK }}
          win_csc_key_password: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
          github_token: ${{ secrets.GH_TOKEN }}
